# Generated by Django 4.1.5 on 2023-02-04 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=55)),
                ('artista', models.CharField(max_length=55)),
                ('fechaLanzamiento', models.IntegerField(blank=True)),
                ('genero', models.CharField(max_length=55)),
                ('subGenero', models.CharField(max_length=255)),
                ('formato', models.CharField(max_length=55)),
                ('paisOrigen', models.CharField(max_length=55)),
                ('disponibilidad', models.BooleanField()),
                ('codigo', models.CharField(max_length=15)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
    ]
