# Generated by Django 4.1.5 on 2023-02-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppTienda', '0002_alter_tienda_codigo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55)),
                ('apellido', models.CharField(max_length=55)),
                ('mail', models.EmailField(max_length=60)),
                ('usuario', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=55)),
                ('telefono', models.IntegerField(blank=True)),
                ('mail', models.EmailField(max_length=60)),
                ('usuario', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Cotizar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=55)),
                ('artista', models.CharField(max_length=55)),
                ('formato', models.CharField(max_length=55)),
                ('descripcion', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(blank=True)),
                ('mail', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Preventa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(max_length=55)),
                ('artista', models.CharField(max_length=55)),
                ('formato', models.CharField(max_length=55)),
                ('descripcion', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.IntegerField(blank=True)),
                ('mail', models.EmailField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Suscribete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=60)),
                ('nombre', models.CharField(max_length=55)),
            ],
        ),
    ]
